micronaut:
  application:
    name: test_proj
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '12ed1zz1'


redis:
  uri: redis://localhost
  caches:
    users-cache:
      # expire one hour after write
      expire-after-write: 20s

graphql:
  enabled: true
  path: /graphql


