micronaut:
  application:
    name: test_proj
  security:
    enabled: true
    intercept-url-map:
      - pattern: /graphql
        access:
          - isAuthenticated()
      - pattern: /login
        access:
          - isAnonymous()
      - pattern: /user/create
        access:
          - isAuthenticated()

    reject-not-found: true
    authentication: cookie
    token:
      enabled: true
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              jws-algorithm: HS256



datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '12ed1zz1'


redis:
  uri: redis://localhost
  caches:
    users-cache:
      # expire one hour after write
      expire-after-write: 20s

graphql:
  enabled: true
  path: /graphql


