micronaut:
  application:
    name: test_proj
  security:
    enabled: true
    intercept-url-map:
      - pattern: /graphql
        access:
          - isAnonymous()
      - pattern: /user/create/
        access:
          - isAuthenticated()

    reject-not-found: true
    authentication: cookie


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '12ed1zz1'


redis:
  uri: redis://localhost
  caches:
    users-cache:
      # expire one hour after write
      expire-after-write: 20s

graphql:
  enabled: true
  path: /graphql


